version: "3"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    ports: 
      - 8080:32400
    environment:
      - VERSION=docker
    restart: always
    volumes:
      - ./:/media/